name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Add main.py to zip
        uses: zip -r deployment.zip
      - name: Update lambda function
        uses: aws lambda update-function-code --function-name unkd-test-assigment --zip-file fileb://deployment.zip
